language: python
sudo: false
services:
  - mysql
  - postgresql
python:
- '3.7'
- '3.8'
env:
- DJANGO_VERSION=1.11 DATABASE_URL=postgres://postgres@127.0.0.1/dbq
- DJANGO_VERSION=2.2 DATABASE_URL=postgres://postgres@127.0.0.1/dbq
- DJANGO_VERSION=1.11 DATABASE_URL=mysql://root@127.0.0.1/dbq
- DJANGO_VERSION=2.2 DATABASE_URL=mysql://root@127.0.0.1/dbq
install:
- pip install -r test-requirements.txt
- pip install -U django==$DJANGO_VERSION
script: python manage.py test
deploy:
  provider: pypi
  user: dabapps
  password:
    secure: YkRDJO+QK2Rr3AJwmxoghTWCCTZFLfXUlqky/my6g7oeMI5Q/F2WzNBmvr84v069fckobHhlN4hhH/JFEaRnCNuYmPhFdiNQh5M5cP/qhUqqh7LsMiX5mJSfM6yCp+rAL6F+yb5r59t3IQKmXKiFzRm/AuS4nHINDFHXwaPjWTw=
  on:
    tags: true
    repo: dabapps/django-db-queue
