language: python
python:
- '2.7'
- '3.4'
install:
- pip install -r test-requirements.txt
script: python manage.py test
deploy:
  provider: pypi
  user: dabapps
  password:
    secure: YkRDJO+QK2Rr3AJwmxoghTWCCTZFLfXUlqky/my6g7oeMI5Q/F2WzNBmvr84v069fckobHhlN4hhH/JFEaRnCNuYmPhFdiNQh5M5cP/qhUqqh7LsMiX5mJSfM6yCp+rAL6F+yb5r59t3IQKmXKiFzRm/AuS4nHINDFHXwaPjWTw=
  on:
    tags: true
    repo: dabapps/django-db-queue
